project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "licence.qmd"

website:
  page-navigation: true
  title: "The Near-Future of Regulatory Submissions: Embracing Reproducibility, Open Source, and Interactivity"
  description: "Homepage for the R in Pharma 2024 Workshop"
  site-url: "https://melkiades.github.io/regulatory-submissions-rinpharma2024/"
  favicon: "images/NEST-logo.png"

  repo-url: https://github.com/Melkiades/regulatory-submissions-rinpharma2024
  repo-actions: [edit, issue]

  open-graph: true
  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/). Inspired by [@minebocek](https://twitter.com/minebocek) and [@statistishdan](https://github.com/ddsjoberg/clinical-reporting-gtsummary-rmed)."
    right: "&copy; Copyright 2022, NEST team"
    background: "#708090"

  sidebar:
    background: "#708090"
    logo: "images/NEST.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/Melkiades/regulatory-submissions-rinpharma2024
        text: GitHub
    style: docked
    contents:
     - href: index.qmd
       text: Home


format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: scroll
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y

editor: source

