# Getting there!

_From an humble data.frame to mesmerizing interactive tables!_

## Preparation

<br>

**Recommended:** Enter the dedicated RStudio Cloud work space (with packages pre-installed) to complete Exercise 1. It may still be helpful to peek at the [exercises web page](https://melkiades.github.io/regulatory-submissions-rinpharma2024/exercises.html){target="_blank"} to verify that your results match the desired output.

<br>

&rarr;  [R in Pharma RStudio Cloud work space](https://posit.cloud/spaces/562648/join?access_code=fDZ1hAmNReOf6JuvxQXcHXTZezAu1qs0vrnUfyXh){target="_blank"}  &larr;

<br>

**Otherwise:** Use your personal computer and follow along the [exercises on the
website](https://melkiades.github.io/regulatory-submissions-rinpharma2024/exercises.html){target="_blank"}. Challenge yourself not to peek at the code solutions until you have completed the exercise.

 
## Exercise 1

<br>
<br>

Create a demographic table by using only {dplyr}. 

<br>

* The data should have only age, gender, and treatment columns. 
* The table should include the mean and standard deviation of age, the count and percentage.

```{r}
#| echo: false
#| cache: false
countdown::countdown(minutes = 5, font_size = "1.5em")
```


<!-- ::: {style="text-align: center; margin-top: 1em"} -->
<!-- [Matplotlib: Visualization with Python](https://matplotlib.org/){preview-link="true" style="text-align: center"} -->
<!-- ::: -->
